guard :coffeescript, :input => "app/assets/coffee", :output => "public/src/js"
guard :less, :all_on_start => true, :all_on_start => false, :output => 'public/src/css' do
  watch(%r[^app/assets/less/(.+\.less)$])
end
guard :concat, :type => "css", :files => %w[lib/bootstrap main], :input_dir => "public/src/css", :output => "public/assets/css/application"
guard :concat, :type => "js", :files => %w[lib/jquery], :input_dir => "public/src/js", :output => "public/src/js/application"
guard :concat, :type => "css", :files => %w[main], :input_dir => "public/src/css", :output => "public/assets/css/test"
guard :concat, :type => "js", :files => %w[main], :input_dir => "public/src/js", :output => "public/src/js/test"
